name: Run Rest assured test cases
on:
  push:
    branches: [ "main" ]
jobs:
  RunRestAssuredTestJob:
    runs-on: windows-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven Test
        run: mvn clean test




#name: Run Rest Assured Test Cases
#'on':
#    push:
#      branches:
#        - master
#jobs:
#    build:
#      runs-on: windows-latest
#      steps:
#        - uses: actions/checkout@v3
#        - uses: actions/setup-java@v3
#          with:
#            java-version: '16'
#            distribution: temurin
#            cache: maven
#        - name: Build with Maven
#          run: mvn clean test